package org.jbpm.examples.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeReward implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String recipient;

	private java.lang.Integer reward;

	private java.lang.String pmComment;

	private java.lang.String hrComment;

	public java.lang.String getRecipient() {
		return this.recipient;
	}

	public void setRecipient(java.lang.String recipient) {
		this.recipient = recipient;
	}

	public java.lang.Integer getReward() {
		return this.reward;
	}

	public void setReward(java.lang.Integer reward) {
		this.reward = reward;
	}

	public java.lang.String getPmComment() {
		return this.pmComment;
	}

	public void setPmComment(java.lang.String pmComment) {
		this.pmComment = pmComment;
	}

	public java.lang.String getHrComment() {
		return this.hrComment;
	}

	public void setHrComment(java.lang.String hrComment) {
		this.hrComment = hrComment;
	}

	public EmployeeReward() {
	}

	public EmployeeReward(java.lang.String recipient, java.lang.Integer reward,
			java.lang.String pmComment, java.lang.String hrComment) {
		this.recipient = recipient;
		this.reward = reward;
		this.pmComment = pmComment;
		this.hrComment = hrComment;
	}

}